AllCops:
  RunRailsCops: true
  Exclude:
    - Rakefile
    - bin/**/*
    - db/**/*
    - config/**/*
    - test/**/*
    - tmp/**/*
    - vendor/**/*
    - app/assets/config.rb



Metrics/AbcSize:
  Max: 25
  Severity: error

Metrics/ClassLength:
  Max: 200
  Severity: error

Metrics/CyclomaticComplexity:
  Max: 10
  Severity: error

Metrics/LineLength:
  Max: 120 # try to reduce to 100
  Severity: warning

Metrics/MethodLength:
  Max: 25 # try to reduce to 10
  Severity: error

Metrics/ModuleLength:
  Max: 200
  Severity: error

Metrics/PerceivedComplexity:
  Max: 10


# Keep for now, easier with superclass definitions
ClassAndModuleChildren:
  Enabled: false

# The ones we use must exist for the entire class hierarchy.
ClassVars:
  Enabled: false

# map instead of collect, reduce instead of inject.
# Probably later
CollectionMethods:
  Enabled: false

# This cop is currently buggy (0.21.0)
Delegate:
  Enabled: false

# Well, well, well
Documentation:
  Enabled: false

# Probably later
DotPosition:
  Enabled: false

# That's no huge stopper
EmptyLines:
  Enabled: false

# Missing UTF-8 encoding statements should always be created.
Encoding:
  Severity: error

# Keep single line bodys for if and unless
IfUnlessModifier:
  Enabled: false

# We thinks that's fine
HasAndBelongsToMany:
  Enabled: false

# We do. But some other methods are still called 'attr', do not complain about them
Style/Attr:
  Enabled: false

# We think that's fine most of the time
Style/GuardClause:
  Enabled: false
