# ############################## #
# Global settings for puzzleTime #
# ############################## #

# Array of holidays with a fixed date. [day, month]
regular_holidays:
  -
    - 1
    - 1
  -
    - 2
    - 1
  -
    - 1
    - 8
  -
    - 25
    - 12
  -
    - 26
    - 12

# LDAP configuration
ldap:
  connection:
    host: ldapi.rz.puzzle.ch
    port: 636
    encryption: simple_tls
  user_dn: ou=puzzle,ou=users,dc=puzzle,dc=itc
  external_dn: ou=extern,ou=users,dc=puzzle,dc=itc
  group: cn=puzzletime,ou=groups,dc=puzzle,dc=itc

# Highrise configuration
highrise:
  url: <%= ENV['RAILS_HIGHRISE_URL'] || 'https://highrisehq.com' %>
  api_token: <%= ENV['RAILS_HIGHRISE_TOKEN'] %>

small_invoice:
  url: https://api.smallinvoice.com
  api_token: <%= ENV['RAILS_SMALL_INVOICE_TOKEN'] %>
  constants:
    currency: CHF
    account_id: 485417264
    esr: true
    esr_number: 0145031
    esr_singlepage: false
    lsvplus: false
    debit_direct: false
    language: de
    paypal: false
    paypal_url:
    client_type: 1 # company
    vat: 8


# Default values
defaults:
  report_type: absolute_day
  start_hour: 8
  country: CH

work_items:
  path_separator: '-'
