# ############################## #
# Global settings for puzzleTime #
# ############################## #

# Array of holidays with a fixed date. [day, month]
regular_holidays:
  -
    - 1
    - 1
  -
    - 2
    - 1
  -
    - 1
    - 8
  -
    - 25
    - 12
  -
    - 26
    - 12

# LDAP configuration
ldap:
  connection:
    host: ldapi.rz.puzzle.ch
    port: 636
    encryption: simple_tls
  user_dn: ou=puzzle,ou=users,dc=puzzle,dc=itc
  external_dn: ou=extern,ou=users,dc=puzzle,dc=itc
  group: cn=puzzletime,ou=groups,dc=puzzle,dc=itc

# Highrise configuration
highrise:
  url: <%= ENV['RAILS_HIGHRISE_URL'] || 'https://highrisehq.com' %>
  api_token: <%= ENV['RAILS_HIGHRISE_TOKEN'] %>

small_invoice:
  url: https://api.smallinvoice.com
  api_token: <%= ENV['RAILS_SMALL_INVOICE_TOKEN'] %>
  constants:
    account_id: 485417264
    esr: true
    esr_singlepage: false
    lsvplus: false
    debit_direct: false
    language: de
    paypal: false
    paypal_url:
    client_type: 1 # company
    position_type_id: 1 # service
    unit_id: 1 # hours
    gender_id: 2 # female
    show_department: true


# Default values
defaults:
  report_type: absolute_day
  start_hour: 8
  country: CH
  vat: 8 # percent
  currency: CHF
  payment_period: 30 # days
  payment_periods:
    - 30
    - 45
    - 60

work_items:
  path_separator: '-'

employees:
  # The initial vacation days are used to transfer the current vacation balance of each employee
  # when introducing puzzle time. At some point, it will no be required to edit that value anymore.
  initial_vacation_days_editable: false
